-- Appointment Booking App: initial relational schema

create extension if not exists pgcrypto;

create type public.appointment_status as enum (
  'scheduled',
  'completed',
  'cancelled'
);

create table public.patients (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) between 2 and 100),
  mobile_number text not null check (mobile_number ~ '^[6-9][0-9]{9}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index patients_mobile_number_idx
  on public.patients (mobile_number);

create table public.doctors (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (char_length(trim(name)) between 2 and 100),
  specialization text not null check (
    char_length(trim(specialization)) between 2 and 100
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.appointments (
  id uuid primary key default gen_random_uuid(),
  booking_number bigint generated by default as identity unique,
  reference_code text generated always as (
    'APT-' || lpad(booking_number::text, 6, '0')
  ) stored unique,
  patient_id uuid not null references public.patients(id) on delete restrict,
  doctor_id uuid not null references public.doctors(id) on delete restrict,
  appointment_date date not null,
  start_time time not null,
  status public.appointment_status not null default 'scheduled',
  description varchar(500),
  cancellation_reason varchar(200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint valid_appointment_slot check (
    extract(second from start_time) = 0
    and extract(minute from start_time) in (0, 30)
    and (
      (start_time >= time '10:00' and start_time < time '13:00')
      or
      (start_time >= time '14:00' and start_time < time '17:00')
    )
  ),

  constraint cancellation_reason_only_when_cancelled check (
    status = 'cancelled' or cancellation_reason is null
  )
);

-- Only scheduled appointments reserve a doctor's slot. Cancelling an
-- appointment keeps its history while making the slot bookable again.
create unique index appointments_unique_scheduled_slot_idx
  on public.appointments (doctor_id, appointment_date, start_time)
  where status = 'scheduled';

create index appointments_patient_id_idx
  on public.appointments (patient_id);

create index appointments_date_time_idx
  on public.appointments (appointment_date, start_time);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger patients_set_updated_at
before update on public.patients
for each row execute function public.set_updated_at();

create trigger doctors_set_updated_at
before update on public.doctors
for each row execute function public.set_updated_at();

create trigger appointments_set_updated_at
before update on public.appointments
for each row execute function public.set_updated_at();

insert into public.doctors (name, specialization)
values
  ('Dr. Ananya Sharma', 'General Medicine'),
  ('Dr. Rahul Mehta', 'Cardiology'),
  ('Dr. Priya Nair', 'Dermatology');

-- Lock tables until explicit Row Level Security policies are added.
alter table public.patients enable row level security;
alter table public.doctors enable row level security;
alter table public.appointments enable row level security;
